START_TEXT = "Hi {}! \n\nI’m File Store Box, the perfect place to store your files and videos. With unlimited storage, I’m not just a bot—I’m your next-level storage partner!"
FORCE_MSG = """
**ʜᴇʏ** {}

**ᴀᴄᴄᴏʀᴅɪɴɢ ᴛᴏ ᴍʏ ᴅᴀᴛᴀʙᴀsᴇ ʏᴏᴜ'ᴠᴇ ɴᴏᴛ ᴊᴏɪɴᴇᴅ ᴜᴘᴅᴀᴛᴇs ᴄʜᴀɴɴᴇʟ ʏᴇᴛ, ɪғ ʏᴏᴜ ᴡᴀɴᴛ ᴛᴏ ᴜsᴇ ᴍᴇ ᴛʜᴇɴ ᴊᴏɪɴ ᴜᴘᴅᴀᴛᴇs ᴄʜᴀɴɴᴇʟ ᴀɴᴅ sᴛᴀʀᴛ ᴍᴇ ᴀɢᴀɪɴ !**
"""


TOOLS_TEXT = """
**I am a File Store Box Bot with an unlimited database where users can store their media files securely.**

**Key Features:**

1. Batch Command (/batch):
This command allows you to save multiple files at once.

2. Media Links:
Whenever you send or forward a media file, the bot automatically creates a unique link for it. You can use this link to access your media at any time.

**Tools/Options:**

**Database (Mandatory):**
Adding your files to the database is required to generate links.

**Shortener (Optional):**
You can choose to shorten the generated links.

**Force Channel (Optional):**
Use this feature if necessary for specific actions or settings.

**This bot simplifies file management and ensures your media is always accessible through shareable links.**
"""


DATABASE_TEXT = "**In a database tool, you can set a channel ID where all your media data will be stored, and from there, you'll be able to access your media.**"
FORCE_TEXT = "**In a force sub-channel, you can make users join your channel forcibly, and only then will they be able to use your bot.**"
SHORTENER_TEXT = "**In a shortener tool, you can add your shortener url and key, which the bot will use to provide users with short urls.**"
POST_TEXT = """
**This is the link generated by you.**

<i>Notice: If you change your database channel, your previous media files will not be available until you switch back to your previous database channel.</i>

**Click the button below to access your media files.**
"""
